"""A12: the dipole-moment active-space selection -- the reading half (menu 20).

The protocol (Kaufold et al., 2023; Kaufold & Dong, 2026) picks the active
space whose dipole moment is closest to a reliable reference:

    dev_n = |mu(S0, A_n) - mu(S0, ref)|,      choose  argmin_n dev_n

(the directional variant replaces the magnitude difference by the projected
difference of the vectors).  The 2026 sequel runs the candidate spaces as
CASCI on MP2 orbitals and recommends CASCI-GDM-AS as the default protocol.

This module reads the batch that menu 19 generated: every candidate output
contributes its **single-root** dipole moment (ORCA's "DIPOLE MOMENT" block,
``State: 0``, relaxed density -- measured); a state-averaged output carries
only the state-average dipole (``State: -1``) and is refused with the rerun
instruction.  The reference comes either from an output (its SCF block) or
from a number the user supplies (an experimental value).

The variants this module does not implement, and why
----------------------------------------------------

- **EDM-AS / D2DM-AS** compare *per-state* dipole moments of the candidates
  with *per-state* TDDFT dipoles.  Measured on ORCA 6.1.1: a state-averaged
  CASSCF/CASCI run prints only the state-average dipole (one block, ``State:
  -1``), and the TDDFT module prints transition dipoles but no state dipoles.
  The data for these variants is therefore not obtainable from ORCA outputs;
  the substitute (per-state densities crossed with the exported dipole
  integrals) is recorded as future work, and the source's own recommendation
  -- CASCI-GDM-AS as the default -- is what this menu implements.
- The directional variants are implemented (``vgdm``) but the source found no
  consistent benefit over the non-directional forms, so ``gdm`` is the default.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from ..knowledge.models import EVIDENCE_LITERATURE, EVIDENCE_MEASURED, Evidence

__all__ = [
    "DmSelectionError",
    "DmSelection",
    "candidate_dipole",
    "reference_dipole",
    "analyze",
    "render",
    "evidence",
]

PROTOCOL_GDM = "gdm"
PROTOCOL_VGDM = "vgdm"
_PROTOCOLS = (PROTOCOL_GDM, PROTOCOL_VGDM)
_KNOWN_BUT_UNIMPLEMENTED = ("edm", "vedm", "d2dm", "vd2dm")


class DmSelectionError(ValueError):
    """The selection cannot be made from the given readings (with a next step)."""


def _blocks(sections) -> tuple:
    return sections.get("dipole", {}).get("blocks", ())


def candidate_dipole(sections, where: str) -> tuple[float, tuple[float, float, float], str]:
    """The single-root dipole of one candidate output: ``(Debye, vector, method)``.

    Refuses an average-only output (the rerun instruction is the next step).
    """
    blocks = _blocks(sections)
    if not blocks:
        raise DmSelectionError(
            f"the output '{where}' carries no DIPOLE MOMENT block, so this candidate "
            "cannot be read. Next step: check that the run finished (the block prints "
            "near the end) and that it is a CASSCF/CASCI run."
        )
    single = [block for block in blocks if block.get("state", 0) == 0]
    if not single:
        states = sorted({block.get("state") for block in blocks})
        raise DmSelectionError(
            f"the output '{where}' prints only state-averaged dipole blocks (states "
            f"{states}) -- the per-state dipoles this protocol needs are not there. Next "
            "step: rerun the candidate with ``nroots 1`` (the batch generated by menu 19 "
            "does), or read the space another way."
        )
    block = single[-1]
    return float(block["magnitude_debye"]), tuple(float(x) for x in block["total"]), str(
        block.get("method", "")
    )


def reference_dipole(sections, where: str) -> tuple[float, tuple[float, float, float], str]:
    """The reference dipole of an output: the SCF block when present, else the last.

    An MP2 output carries several blocks (SCF, MP2 unrelaxed, MP2 relaxed): the
    SCF block is the KS-DFT-style reference the source used; a CASSCF reference
    output has a single State-0 block.
    """
    blocks = _blocks(sections)
    if not blocks:
        raise DmSelectionError(
            f"the reference output '{where}' carries no DIPOLE MOMENT block. Next step: "
            "give a converged SCF/DFT output (the SCF block is used), or supply the "
            "reference value directly in the manifest."
        )
    scf = [block for block in blocks if block.get("method") == "SCF"]
    pool = scf or [block for block in blocks if block.get("state", 0) >= 0] or list(blocks)
    block = pool[-1]
    return float(block["magnitude_debye"]), tuple(float(x) for x in block["total"]), str(
        block.get("method", "")
    )


@dataclass(frozen=True)
class DmSelection:
    """The ranked candidates and the chosen space."""

    results: tuple  # (deviation, nel, norb, magnitude), best first
    selected: tuple
    deviation: float
    reference_magnitude: float
    reference_source: str
    protocol: str
    checks: tuple
    notes: tuple


def analyze(readings, reference, *, protocol: str = PROTOCOL_GDM) -> DmSelection:
    """Rank the candidates and pick the one closest to the reference.

    ``readings``: iterable of ``(nel, norb, magnitude_debye, vector)``;
    ``reference``: ``(magnitude_debye, vector, source)``.  The reference vector
    may be ``None`` (a supplied experimental magnitude only).
    """
    key = protocol.strip().lower()
    if key in _KNOWN_BUT_UNIMPLEMENTED:
        raise DmSelectionError(
            f"the protocol '{protocol}' needs per-state dipole moments, which ORCA does "
            "not print: a state-averaged CASSCF run gives only the state average "
            "(State: -1) and TDDFT gives transition dipoles only. Next step: use 'gdm' "
            "(the source's own default recommendation); the per-state route is recorded "
            "as future work."
        )
    if key not in _PROTOCOLS:
        raise DmSelectionError(
            f"the protocol '{protocol}' is not known. Next step: use 'gdm' (default) or "
            "'vgdm'."
        )
    reference_magnitude, reference_vector, reference_source = reference
    if key == PROTOCOL_VGDM and reference_vector is None:
        raise DmSelectionError(
            "the directional protocol needs the reference dipole as a vector, but only a "
            "magnitude was supplied. Next step: give the reference output (its vector is "
            "read) or switch to 'gdm'."
        )
    results = []
    for nel, norb, magnitude, vector in readings:
        if key == PROTOCOL_GDM:
            deviation = abs(magnitude - reference_magnitude)
        else:
            reference_array = np.array(reference_vector, dtype=float)
            norm = float(np.linalg.norm(reference_array))
            if norm <= 0.0:
                raise DmSelectionError(
                    "the reference dipole vector has zero length, so the directional "
                    "comparison is undefined. Next step: check the reference."
                )
            projected = float(np.dot(np.array(vector, dtype=float), reference_array) / norm)
            deviation = abs(projected - norm)
        results.append((deviation, nel, norb, magnitude))
    if not results:
        raise DmSelectionError(
            "no candidate readings were given. Next step: fill the manifest with the "
            "candidate outputs."
        )
    # smallest deviation wins; ties go to the smaller space (the protocol's point is a
    # suitable space, not an unnecessarily large one)
    results.sort(key=lambda item: (item[0], item[2], item[1]))
    selected = results[0]
    checks = (
        f"the protocol is {key.upper()}-AS: "
        + (
            "the absolute difference of the total dipole moments"
            if key == PROTOCOL_GDM
            else "the projected difference of the dipole-moment vectors"
        )
        + f" against the reference ({reference_magnitude:.4f} D from {reference_source}); "
        "the smallest deviation wins and ties go to the smaller space",
        "each candidate is read from its single-root dipole block (State: 0, relaxed "
        "density); state-averaged outputs are refused (they print only the average)",
    )
    notes = (
        "The source runs the candidates as state-averaged calculations over six states "
        "and takes the S0 dipole of that ensemble; the ORCA route here runs each "
        "candidate with nroots 1 (the only form whose S0 dipole ORCA prints). The two "
        "differ by the state-averaging relaxation of the density -- the ranking between "
        "candidates is what the protocol uses.",
        "The reference value drives the choice: the source tested experimental (NIST) "
        "dipole moments and KS-DFT values with several functionals, and the 2026 "
        "recommendations name R2SCAN-family references as unsuitable for the EDM "
        "variant. State the reference and its origin in the report when publishing.",
        "The protocol needs a nonzero dipole moment, and the source excludes charged "
        "systems (the dipole of a charged molecule depends on the coordinate origin).",
        "For a potential-energy scan the protocol offers no guarantee that every "
        "geometry selects the same active space; select at one geometry and carry the "
        "space with the cross-structure mapping (menu 17) when consistency matters.",
        "The per-state variants (EDM-AS, D2DM-AS) are not implemented: their data is not "
        "printed by ORCA (see the module docstring). The source's own recommendation "
        "names CASCI-GDM-AS the default protocol.",
    )
    return DmSelection(
        results=tuple(results),
        selected=(selected[1], selected[2]),
        deviation=selected[0],
        reference_magnitude=reference_magnitude,
        reference_source=reference_source,
        protocol=key,
        checks=checks,
        notes=notes,
    )


def render(selection: DmSelection) -> str:
    """The ranking table and the chosen space."""
    lines = [
        "Dipole-moment active-space selection (DM-AS):",
        f"  reference: {selection.reference_magnitude:.4f} D  ({selection.reference_source})",
        f"  protocol:  {selection.protocol.upper()}-AS",
        "",
        "  rank   active space     mu (D)   deviation (D)",
    ]
    for rank, (deviation, nel, norb, magnitude) in enumerate(selection.results, start=1):
        marker = "  <- selected" if (nel, norb) == selection.selected else ""
        lines.append(f"  {rank:>4}   ({nel:>2}e, {norb:>2}o)   {magnitude:>8.4f}   {deviation:>11.4f}{marker}")
    lines += [
        "",
        f"Selected active space: ({selection.selected[0]}e, {selection.selected[1]}o)  "
        f"[deviation {selection.deviation:.4f} D]",
        "",
        "Criteria and boundaries:",
    ]
    for item in selection.checks + selection.notes:
        lines.append(f"  - {item}")
    return "\n".join(lines)


def evidence() -> tuple[Evidence, ...]:
    """Provenance of the protocol and of the ORCA readings."""
    return (
        Evidence(
            kind=EVIDENCE_LITERATURE,
            text=(
                "The dipole-moment active-space selection: candidates are ranked by the "
                "absolute deviation of their dipole moment from a reference (experiment "
                "or KS-DFT); the directional variant projects the vectors. GDM-AS uses "
                "the ground-state dipole, EDM-AS the per-state maxima, and the D2DM "
                "variant the state whose dipole differs most from the ground state (for "
                "charge-transfer cases)."
            ),
            ref=(
                "Kaufold B. W., Chintala N., Pandeya P., Dong S. S., J. Chem. Theory "
                "Comput., 2023, 19, 2469-2483, DOI 10.1021/acs.jctc.2c01128"
            ),
            url="https://doi.org/10.1021/acs.jctc.2c01128",
            bibkey="kaufold2023dipole",
        ),
        Evidence(
            kind=EVIDENCE_LITERATURE,
            text=(
                "The CASCI version on MP2 orbitals (the scan becomes cheap), the PASS "
                "candidate family, and the recommendations: CASCI-GDM-AS is the sensible "
                "default (simplest, no excited-state reference needed); CASCI-EDM-AS for "
                "CASPT2 excitation energies with non-R2SCAN references; the D2DM variants "
                "for charge-transfer states; the directional variants show no consistent "
                "benefit. The authors note that for potential-energy scans the protocols "
                "do not guarantee the same space at every geometry."
            ),
            ref=(
                "Kaufold B. W., Dong S. S., J. Chem. Theory Comput., 2026, 22, 7624-7641, "
                "DOI 10.1021/acs.jctc.6c00473"
            ),
            url="https://doi.org/10.1021/acs.jctc.6c00473",
            bibkey="kaufold2026casci",
        ),
        Evidence(
            kind=EVIDENCE_MEASURED,
            text=(
                "The ORCA readings, measured on 6.1.1 (H2O fixtures, 2026-09-27): a "
                "single-root CASCI prints its own DIPOLE MOMENT block (State: 0, relaxed "
                "density, magnitude in Debye); a state-averaged run prints one block with "
                "the state average (State: -1) and is refused; the SCF/DFT reference "
                "reads its own SCF block; TDDFT prints transition dipoles only. On the "
                "fixture pair, PBE0/def2-TZVP gives 2.0801 D against the CASCI(6,6) "
                "value 2.1046 D."
            ),
            ref="tests/test_dm_selection.py; fixtures/orca/h2o_dm_*",
        ),
    )
