"""generating an automr input (menu 44).

MOKIT (Apache-2.0) consumes one Gaussian-style ``.gjf`` carrying a
``mokit{}`` block; ``automr x.gjf > x.out`` then runs the black-box
multireference workflow.  The template below is the shape the program's own
example set uses and the one the measured run of 2026-09-30 accepts
(MOKIT 1.2.8; H2O with ``mokit{GVB_prog=Gaussian}``; fixtures
``fixtures/mokit/``):

    %mem=4GB
    %nprocshared=2
    #p CASSCF/cc-pVDZ

    mokit{GVB_prog=Gaussian}

    0 1
    O   x y z
    ...

Boundaries built into the generator (measured / manual-backed):

- ``GVB_prog`` accepts GAMESS (the default), Gaussian and QChem -- PySCF is
  not a GVB backend (manual section 4.4.10); a different value is refused
  with the reason.  The default here is Gaussian because it is the backend
  the measured run used on this group's machines (GAMESS is not installed).
- the ``mokit{}`` option list is passed through verbatim after a shape
  check (comma-separated ``key=value`` entries or bare flags such as
  ``charge``/``cart``); the program lower-cases and merges them itself.
- the route line is ``method/basis`` with the method written as the user
  gives it (``CASSCF``, ``CASSCF(6,6)``, ``NEVPT2`` ...); writing the pair
  pins the active-space size, omitting it lets automr select automatically.

The run itself needs a Python with the MOKIT extension modules (built for
one Python version, against NumPy 1) plus at least one HF backend; the
guidance lines state the environment that the measured run used.
"""

from __future__ import annotations

import re
from typing import Sequence

from ..knowledge.models import EVIDENCE_MEASURED, Evidence

__all__ = [
    "MokitInputError",
    "input_gjf",
    "render",
    "run_guidance_lines",
    "evidence",
]

_ATOM_RE = re.compile(r"^[A-Z][a-z]?$")
_OPTION_ENTRY_RE = re.compile(r"^[A-Za-z_][\w.]*(=.*)?$")
_GVB_PROGRAMS = {"gamess": "GAMESS", "gaussian": "Gaussian", "qchem": "QChem"}


class MokitInputError(ValueError):
    """The requested automr input cannot be built as asked (with a next step)."""


def input_gjf(
    *,
    atoms: Sequence[tuple[str, float, float, float]],
    method: str,
    basis: str,
    mokit_options: str,
    charge: int,
    mult: int,
    memory_gb: int = 4,
    nproc: int = 2,
    comment: str = "generated by fBlockKit (menu 44)",
) -> str:
    """The .gjf text (Gaussian-style route + mokit{} block + geometry)."""
    if not atoms:
        raise MokitInputError("no atoms given. Next step: give a structure source with atoms.")
    method = method.strip() or "CASSCF"
    basis = basis.strip() or "cc-pVDZ"
    if "/" in method:
        raise MokitInputError(
            "the method must not carry the basis (write 'CASSCF' or 'CASSCF(6,6)' in the "
            "method field and the basis separately)."
        )
    if memory_gb <= 0 or nproc <= 0:
        raise MokitInputError("memory and nproc must be positive integers.")
    options = _mokit_options(mokit_options)
    lines = [
        f"%mem={memory_gb}GB",
        f"%nprocshared={nproc}",
        f"#p {method}/{basis}",
        "",
        options,
        "",
        f"{charge} {mult}",
    ]
    for element, x, y, z in atoms:
        element = element.strip()
        if not _ATOM_RE.match(element):
            raise MokitInputError(f"{element!r} is not an element symbol.")
        lines.append(f"{element:<2} {x:>16.8f} {y:>16.8f} {z:>16.8f}")
    lines.append("")
    if comment.strip():
        lines.append(f"! {comment.strip()}")
    return "\n".join(lines)


def _mokit_options(raw: str) -> str:
    """The normalised ``mokit{...}`` line (shape-checked, GVB value pinned)."""
    entries = [entry.strip() for entry in raw.split(",") if entry.strip()]
    normalised: list[str] = []
    for entry in entries:
        if not _OPTION_ENTRY_RE.match(entry):
            raise MokitInputError(
                f"mokit{{}} entry {entry!r} is not of the form key=value "
                "(or a bare flag such as charge/cart)."
            )
        key, _, value = entry.partition("=")
        if key.strip().lower() == "gvb_prog":
            pinned = _GVB_PROGRAMS.get(value.strip().strip("'\"").lower())
            if pinned is None:
                raise MokitInputError(
                    "GVB_prog accepts GAMESS (default), Gaussian and QChem only "
                    "(PySCF is not a GVB backend). Next step: choose one of the three, "
                    "or drop the keyword to keep the GAMESS default."
                )
            normalised.append(f"GVB_prog={pinned}")
        else:
            normalised.append(entry)
    return "mokit{" + ",".join(normalised) + "}"


def render(
    *,
    gjf_text: str,
    gjf_name: str,
    n_atoms: int,
    method: str,
    basis: str,
) -> str:
    """The generation report (content + the run-side guidance)."""
    lines = [
        "MOKIT automr input (B-layer generation)",
        "",
        f"Written: {gjf_name} ({n_atoms} atoms, {method}/{basis})",
        "",
        "The file (Gaussian-style route line + the mokit{} block):",
        "",
    ]
    lines.extend(gjf_text.rstrip().splitlines())
    lines.append("")
    lines.append("Next steps:")
    for line in run_guidance_lines():
        lines.append(f"  - {line}")
    lines.append("")
    lines.append(
        "Reading notes: automr runs the black-box chain HF -> UNO -> GVB -> "
        "CASCI/CASSCF; the CASSCF(n,m) size, if written in the route, pins the active "
        "space, otherwise the size is determined from the GVB natural-orbital "
        "occupations (threshold 0.02). The output lands in the capture file plus a "
        "family of .fch/.dat side products next to the input."
    )
    return "\n".join(lines)


def run_guidance_lines() -> tuple[str, ...]:
    """The environment and command the measured run used (MOKIT 1.2.8, 2026-09-30)."""
    return (
        "Set MOKIT_ROOT to the extracted MOKIT directory; put $MOKIT_ROOT/bin on PATH.",
        "Export PYTHONPATH=$MOKIT_ROOT and make sure the plain 'python' command is a "
        "Python matching the MOKIT build (the prebuilt packages carry extension modules "
        "for one Python version; they also need NumPy 1.x).",
        "For the Gaussian backend export g16root and GAUSS_SCRDIR; for GAMESS set GMS.",
        "Run: automr name.gjf > name.out  (read the capture back with menu 45).",
    )


def evidence() -> tuple[Evidence, ...]:
    return (
        Evidence(
            kind=EVIDENCE_MEASURED,
            text=(
                "The template and the environment lines are the measured run of "
                "2026-09-30 (MOKIT 1.2.8 prebuilt py310 package; H2O CASSCF/cc-pVDZ "
                "with mokit{GVB_prog=Gaussian} on Gaussian 16 + PySCF): the generated "
                "input was accepted and the workflow reached Normal termination."
            ),
            ref="fixtures/mokit/ (README records the full environment and the run)",
        ),
        Evidence(
            kind=EVIDENCE_MEASURED,
            text=(
                "GVB_prog accepts GAMESS (default), Gaussian and QChem only; PySCF is "
                "not listed as a GVB backend (MOKIT manual section 4.4.10, read "
                "2026-09-30)."
            ),
            ref="MOKIT manual, section 4.4.10 (GVB_prog)",
            url="https://doc.mokit.xyz/chap4-4.html",
        ),
        Evidence(
            kind=EVIDENCE_MEASURED,
            text=(
                "The mokit{} option syntax (comma-separated entries, bare flags such as "
                "charge/cart, readuhf='file.fchk' with quotes, ist=N) is the program's "
                "own example set, read 2026-09-30."
            ),
            ref="MOKIT sources, examples/automr/*.gjf",
            url="https://gitlab.com/jxzou/mokit",
        ),
    )
